version: "3.9"
services:
  orca-graphql:
    build:
      context: .
      dockerfile: Dockerfile.graphql
    ports:
      - "0.0.0.0:5000:5000"
    # environment:
      # - "HOST=0.0.0.0"
      # - "PORT=5000"
      # - "ORCA_ENV=development"