---
version: 2
plan:
  project-key: ORCA
  key: OTA
  name: ORCA Artifact TEST
stages:
- Test stage:
    manual: true
    final: false
    jobs:
    - Test stage job
- Validate test:
    manual: true
    final: true
    jobs:
    - Validate test job
Test stage job:
  key: TSJ
  other:
    clean-working-dir: true
  docker:
    image: maven.earthdata.nasa.gov/cumulus_orca
    volumes:
      ${bamboo.working.directory}: ${bamboo.working.directory}
      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
  tasks:
  - checkout:
      force-clean-build: 'true'
      description: Checkout Default Repository
  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/bash
        export AWS_ACCESS_KEY_ID=$bamboo_CUMULUS_AWS_ACCESS_KEY_ID
        export AWS_SECRET_ACCESS_KEY=$bamboo_CUMULUS_AWS_SECRET_ACCESS_KEY
        export AWS_DEFAULT_REGION=$bamboo_CUMULUS_AWS_DEFAULT_REGION
        . ./integration_test/shared/test.sh
Validate test job:
  key: VTJ
  other:
    clean-working-dir: true
  docker:
    image: maven.earthdata.nasa.gov/cumulus_orca
    volumes:
      ${bamboo.working.directory}: ${bamboo.working.directory}
      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
  tasks:
  - checkout:
      force-clean-build: 'true'
      description: Checkout Default Repository
  # - artifact-download:
  #     source-plan: ORCA-OTA
  #     artifacts:
  #       - name: S3 List
  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/bash
        echo "Hello 2"
        pwd
        ls
        less s3_list.txt

variables:
  AWS_DEFAULT_REGION: us-west-2
  CUMULUS_AWS_DEFAULT_REGION: us-west-2
  CUMULUS_AWS_ACCESS_KEY_ID: REPLACE ME
  CUMULUS_AWS_SECRET_ACCESS_KEY: BAMSCRT@0@0@eYcVOgzAUh3Ar0/flmZ1jQ==  #encrypted
 
repositories:
- orca test 2:
    scope: global
triggers:
- polling: # Does not actually poll, as we do not have webhooks enabled.
    period: '60' #time in seconds
branches:
  create: for-new-branch
  delete:
    after-deleted-days: 7
    after-inactive-days: 30
  link-to-jira: true