---
version: 2
plan:
  project-key: ORCA
  key: RTR
  name: rhassan-test-repository
stages:
#deploy RDS cluster for integration test
#TODO ORCA-462: move to a different stage or even to a new plan for better maintenance.
- Deploy Dev RDS Stack:
    manual: true
    final: false
    jobs:
    - Deploy RDS cluster

#deploy orca and cumulus for integration test
- Deploy Dev Cumulus and ORCA Stack:
    manual: true
    final: false
    jobs:
    - Deploy cumulus and orca
          
#job for deploying cumulus and orca
Deploy RDS cluster:
  key: DRC
  other:
    clean-working-dir: true
  docker:
    image: maven.earthdata.nasa.gov/cumulus_orca
    volumes:
      ${bamboo.working.directory}: ${bamboo.working.directory}
      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
  tasks:
  - checkout:
      force-clean-build: 'true'
      description: Checkout Default Repository
  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/bash
        bash integration_test/deploy-orca.sh

#job for deploying cumulus and orca
Deploy cumulus and orca:
  key: DCO
  other:
    clean-working-dir: true
    # Some plugin configurations are not supported by YAML Specs
  docker:
    image: maven.earthdata.nasa.gov/cumulus_orca
    volumes:
      ${bamboo.working.directory}: ${bamboo.working.directory}
      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
  tasks:
  - checkout:
      force-clean-build: 'true'
      description: Checkout Default Repository

  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/bash
        bash integration_test/deployment-cumulus-orca.sh
variables:
  DEPLOYMENT: sandbox
  ORCA_VERSION: 4.0.3
  RELEASE_FLAG: 'false'
  REPORT_BUILD_STATUS: 'true'
  SECRET_GITHUB_EMAIL: BAMSCRT@0@0@HYUkicwfEqt17JZaZuGYmtmRHrnDySiT+kQkBQa7/Rg7IQgl1lUvbncMUu0Wx2k1ayHojNkh2TdOlF0kJ5tw6Q== #encrypted
  SECRET_GITHUB_TOKEN: BAMSCRT@0@0@nPxyXQXMyE6zm3B1oI8Goma78s0H1fJD4vHy6+dpBQJpjDI2ekbcvCAOI8AyjYiILPhqi2w4fT0fx9MFVXxz2JPTp5uPNzG3GM/8XSUgvYo= #encrypted
  SECRET_GITHUB_USER: BAMSCRT@0@0@fFtitNITDsAjJqK2ZXjhnBZ96z2775QLzGR1Xz557gSl8HxxBaTD3Fbmp+HUbpfx  #encrypted
  AWS_DEFAULT_REGION: us-west-2
  AWS_ACCOUNT_ID: BAMSCRT@0@0@fFtitNITDsAjJqK2ZXjhnBZ96z2775QLzGR1Xz557gSl8HxxBaTD3Fbmp+HUbpfx
  AWS_ACCESS_KEY_ID: REPLACE ME
  AWS_SECRET_ACCESS_KEY: BAMSCRT@0@0@eYcVOgzAUh3Ar0/flmZ1jQ==  #encrypted
  RDS_SECURITY_GROUP: REPLACE ME
  RDS_ENGINE_VERSION: 10.18
  RDS_USER_ACCESS_SECRET_ARN: BAMSCRT@0@0@eYcVOgzAUh3Ar0/flmZ1jQ==  #encrypted
  AWS_SUBNET_ID1: subnet-0d3416cbfaaf3508e
  AWS_SUBNET_ID2: subnet-0b7acca747c16c895
  VPC_ID: vpc-0c4932fcc4b86cff6
  AWS_ACCOUNT_ID: REPLACE ME
  ROLE_BOUNDARY: NGAPShRoleBoundary
  CUMULUS_ORCA_DEPLOY_TEMPLATE_VERSION: release/v11.1.1-v4.0.1
  PREFIX: orcaintegration
  DB_ADMIN_USERNAME: postgres
  DB_ADMIN_PASSWORD: BAMSCRT@0@0@eYcVOgzAUh3Ar0/flmZ1jQ==  #encrypted
  DB_USER_PASSWORD: BAMSCRT@0@0@eYcVOgzAUh3Ar0/flmZ1jQ==  #encrypted
  CMR_PASSWORD: BAMSCRT@0@0@eYcVOgzAUh3Ar0/flmZ1jQ==  #encrypted
  CMR_USERNAME: username
  EARTHDATA_CLIENT_ID: REPLACE ME
  EARTHDATA_CLIENT_PASSWORD: BAMSCRT@0@0@eYcVOgzAUh3Ar0/flmZ1jQ==  #encrypted
  DB_HOST_ENDPOINT: REPLACE ME
  
repositories:
- orca test 2: #this is created by CICD team from https://ci.earthdata.nasa.gov/. Contact Venku Jayanti with any issues.
    scope: global
triggers:
- polling: # Does not actually poll, as we do not have webhooks enabled.
    period: '60' #time in seconds
branches:
  create: for-new-branch
  delete:
    after-deleted-days: 7
    after-inactive-days: 30
  link-to-jira: true
---
version: 2
plan:
  key: ORCA-RTR
plan-permissions:
- users:
  - bhazuka
  - andrew.dorn
  - rizbi.hassan
  - scott.saxon

  permissions:
  - view
  - edit
  - build
  - clone
  - admin
...