---
version: 2
plan:
  project-key: ORCA #this is fixed
  key: RHASSAN
  name: rhassan-test-plan
stages:
- Test stage:
    manual: false
    final: false
    jobs:
    - Test job
Test job:
  key: TJ
  tasks:
  - checkout:
      force-clean-build: 'false'
      description: Checkout Default Repository
  - script:
      interpreter: SHELL
      scripts:
      - |-
        echo "Hello from bamboo new"
      description: Test script
repositories:
- orca branch: #the name must match the repo name given in CI website
    type: git
    url: https://github.com/nasa/cumulus-orca
    branch: feature/ORCA-test-bamboo    #this is the branch where the spec file will reside
triggers:
- polling:
    period: '60'
branches:
  create: for-new-branch
  delete:
    after-deleted-days: 7
    after-inactive-days: 30
---
version: 2
plan:
  key: RHASSAN
plan-permissions:
- users:
  - rizbi.hassan
  permissions:
  - view
  - edit
  - build
  - clone
  - admin

