---
version: 2
plan:
  project-key: ORCA
  key: TEST
  name: test-orca-new
stages:
- Test stage:
    manual: false
    final: false
    jobs:
    - Test job
Test job:
  key: TJ
  tasks:
  - checkout:
      force-clean-build: 'false'
      description: Checkout Default Repository
  - script:
      interpreter: SHELL
      scripts:
      - |-
        echo "Hello from bamboo new"
      description: Test script
repositories:
- ORCA repo:
    type: git
    url: https://github.com/nasa/cumulus-orca
    branch: feature/ORCA-260
triggers:
- polling:
    period: '60'
branches:
  create: for-new-branch
  delete:
    after-deleted-days: 7
    after-inactive-days: 30
---
version: 2
plan:
  key: TEST
plan-permissions:
- users:
  - rizbi.hassan
  - andrew.dorn
  permissions:
  - view
  - edit
  - build
  - clone
  - admin
...
